export function getEnvironmentLabel(tag: string): string {
  const map: Record<string, string> = {
    PET_FRIENDLY: "Permite animais",
    BISTRO: "Bistrô",
    THEMED: "Temático",
    TOUR: "Tours",
    STADIUM: "Estádio",
    LIVE_MUSIC: "Música Ao Vivo",
    KARAOKE: "Karaokê",
    ROCK_BAR: "Rock Bar",
    BOTECO: "Boteco",
    RUSSO: "Russo",
    JAPANESE: "Japonês",
    ITALIAN: "Italiano",
    CHINESE: "Chinês",
    AMERICAN: "Americano",
    FASTFOOD: "Fast Food",
    VEGETARIAN: "Vegetariano",
    VEGAN: "Vegano",
    BRAZILIAN: "Brasileiro",
    SEAFOOD: "Frutos do Mar",
    ASIAN: "Asiático",
    KOREAN: "Coreano",
    MEXICAN: "Mexicano",
    INDIAN: "Indiano",
    LEBANESE: "Libanês",
    TURKISH: "Turco",
    GERMAN: "Alemão",
    SPANISH: "Espanhol",
    FRENCH: "Francês",
    THAI: "Tailandês",
    AMBIANCE: "Ambiente Decorado",
    GREEK: "Grego",
    FILIPINO: "Filipino",
    MALAYSIAN: "Malaio",
    PERUVIAN: "Peruano",
    ARGENTINIAN: "Argentino",
    AFRICAN: "Africano",
    TAIWANESE: "Taiwanês",
    HAMBURGUER: "Hamburgueria",
    MOLECULAR_GASTRONOMY: "Gastronomia Molecular",
    EXPERIENCE: "Jantar com Experiência",
    NORDIC: "Nórdico",
    IRANIAN: "Iraniano",
    ARGENTINE: "Argentino",
    VIETNAMESE: "Vietnamita",
    BOLIVIAN: "Boliviano",
    RUSSIAN: "Russo",
    HISTORIC_PLACE: "Histórico",
    SAMBA: "Samba",
    FORRO: "Forró",
    PAGODE: "Pagode",
    ALLYOUCAN_EAT: "Rodízio",
    URUGUAYAN: "Uruguaio",
    OPEN_24_HOURS: "24 Horas",
    ARMENIAN: "Armênio",
    COLOMBIAN: "Colombiano",
    MILKSHAKE: "Milkshake",
    CULTURE: "Cultural",
    ART_EXHIBITION: "Exposições",
    MUSEUM: "Museu",
    PARK: "Parque",
    ZOO: "Zoológico",
    THEATER: "Teatro",
    RELIGIOUS_SITE: "Religioso",
    SHOP_LOCATION: "Compras",
    OPENED_SPACE: "Espaço Aberto",
    MONUMENT: "Monumento",
    SINGLE_ACTIVITY: "Individual",
    FAMILY_ACTIVITY: "Família",
    GROUP_ACTIVITY: "Grupos",
    COWORKING: "Coworking",
    OTHERS: "Outros",
  };
  return map[tag] || tag;
}
